USE QLSP
GO
CREATE TABLE LoaiSP (
    Maloai NVARCHAR(10) PRIMARY KEY,
    Tenloai NVARCHAR(50) NOT NULL
);

CREATE TABLE Sanpham (
    MaSP NVARCHAR(10) PRIMARY KEY,
    TenSP NVARCHAR(50) NOT NULL,
    Dongia DECIMAL(18, 2) NOT NULL,
    Maloai NVARCHAR(10) FOREIGN KEY REFERENCES LoaiSP(Maloai)
);
